// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQGwDECjQM1A-iAUtAVFUsjPN9gARCCf8',
    appId: '1:493259870647:android:57b1644fa42ede34da5832',
    messagingSenderId: '493259870647',
    projectId: 'to-do-list-b21c6',
    databaseURL:
        'https://to-do-list-b21c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-list-b21c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfuCQntLzxUbFlvy4nNHDoa0dRpsPnpfU',
    appId: '1:493259870647:ios:963f33e89f526e8fda5832',
    messagingSenderId: '493259870647',
    projectId: 'to-do-list-b21c6',
    databaseURL:
        'https://to-do-list-b21c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'to-do-list-b21c6.appspot.com',
    iosClientId:
        '493259870647-7rkus7nsgm9hub2a09j4one3iemmv7jc.apps.googleusercontent.com',
    iosBundleId: 'com.rio.todoList',
  );
}
